In [49]:
import numpy as np
import pandas as pd

In [50]:
bmw = pd.read_csv("BMW_Sales.csv")

In [51]:
bmw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3072 entries, 0 to 3071
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Year              3072 non-null   int64
 1   Month             3072 non-null   int64
 2   Region            3072 non-null   object
 3   Model             3072 non-null   object
 4   Units_Sold        3072 non-null   int64
 5   Avg_Price_EUR     3072 non-null   int64
 6   Revenue_EUR       3072 non-null   int64
 7   BEV_Share         3072 non-null   float64
 8   Premium_Share     3072 non-null   float64
 9   GDP_Growth        3072 non-null   float64
 10  Fuel_Price_Index  3072 non-null   float64
dtypes: float64(4), int64(5), object(2)
memory usage: 264.1+ KB

In [52]:
bmw.head()

,Year,Month,Region,Model,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
0,2018,1,Europe,3 Series,7822,47482,371404204,0.011,19.12,3.5,1.0
1,2018,1,Europe,5 Series,10280,61685,634121800,0.019,19.12,3.5,1.0
2,2018,1,Europe,X3,3105,58433,181434465,0.022,19.12,3.5,1.0
3,2018,1,Europe,X5,7420,67955,504226100,0.021,19.12,3.5,1.0
4,2018,1,Europe,X7,8474,92300,782150200,0.035,19.12,3.5,1.0

In [53]:
bmw.tail()

,Year,Month,Region,Model,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
3067,2025,12,RestOfWorld,X5,9281,68198,632945638,0.201,5.89,2.37,1.41
3068,2025,12,RestOfWorld,X7,12785,91839,1174161615,0.203,5.89,2.37,1.41
3069,2025,12,RestOfWorld,i4,4906,63437,311221922,0.180,5.89,2.37,1.41
3070,2025,12,RestOfWorld,iX,7871,73867,581407157,0.196,5.89,2.37,1.41
3071,2025,12,RestOfWorld,MINI,6732,41811,281471652,0.167,5.89,2.37,1.41

In [54]:
bmw.isnull()

,Year,Month,Region,Model,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
3067,False,False,False,False,False,False,False,False,False,False,False
3068,False,False,False,False,False,False,False,False,False,False,False
3069,False,False,False,False,False,False,False,False,False,False,False
3070,False,False,False,False,False,False,False,False,False,False,False
3071,False,False,False,False,False,False,False,False,False,False,False

In [55]:
type(bmw)

pandas.core.frame.DataFrame

In [56]:
sale = bmw.query("`Premium_Share` > 20.95 ").copy()

In [57]:
sale

,Year,Month,Region,Model,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
2416,2024,4,USA,3 Series,5982,49213,294392166,0.177,20.97,2.92,1.31
2417,2024,4,USA,5 Series,7554,63936,482972544,0.168,20.97,2.92,1.31
2418,2024,4,USA,X3,7766,57330,445224780,0.171,20.97,2.92,1.31
2419,2024,4,USA,X5,4423,68440,302710120,0.171,20.97,2.92,1.31
2420,2024,4,USA,X7,10053,92764,932556492,0.145,20.97,2.92,1.31
2421,2024,4,USA,i4,12513,65121,814859073,0.173,20.97,2.92,1.31
2422,2024,4,USA,iX,9160,74905,686129800,0.168,20.97,2.92,1.31
2423,2024,4,USA,MINI,8025,43504,349119600,0.181,20.97,2.92,1.31

In [58]:
sale.loc[2416]

Year                     2024
Month                       4
Region                    USA
Model                3 Series
Units_Sold               5982
Avg_Price_EUR           49213
Revenue_EUR         294392166
BEV_Share               0.177
Premium_Share           20.97
GDP_Growth               2.92
Fuel_Price_Index         1.31
Name: 2416, dtype: object

In [59]:
sale.iat[5,3]

'i4'

In [60]:
sale.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, 2416 to 2423
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Year              8 non-null      int64
 1   Month             8 non-null      int64
 2   Region            8 non-null      object
 3   Model             8 non-null      object
 4   Units_Sold        8 non-null      int64
 5   Avg_Price_EUR     8 non-null      int64
 6   Revenue_EUR       8 non-null      int64
 7   BEV_Share         8 non-null      float64
 8   Premium_Share     8 non-null      float64
 9   GDP_Growth        8 non-null      float64
 10  Fuel_Price_Index  8 non-null      float64
dtypes: float64(4), int64(5), object(2)
memory usage: 1.0+ KB

In [61]:
sale.head()

,Year,Month,Region,Model,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
2416,2024,4,USA,3 Series,5982,49213,294392166,0.177,20.97,2.92,1.31
2417,2024,4,USA,5 Series,7554,63936,482972544,0.168,20.97,2.92,1.31
2418,2024,4,USA,X3,7766,57330,445224780,0.171,20.97,2.92,1.31
2419,2024,4,USA,X5,4423,68440,302710120,0.171,20.97,2.92,1.31
2420,2024,4,USA,X7,10053,92764,932556492,0.145,20.97,2.92,1.31

In [62]:
sale2 = sale.tail().copy()

In [63]:
sale2

,Year,Month,Region,Model,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
2419,2024,4,USA,X5,4423,68440,302710120,0.171,20.97,2.92,1.31
2420,2024,4,USA,X7,10053,92764,932556492,0.145,20.97,2.92,1.31
2421,2024,4,USA,i4,12513,65121,814859073,0.173,20.97,2.92,1.31
2422,2024,4,USA,iX,9160,74905,686129800,0.168,20.97,2.92,1.31
2423,2024,4,USA,MINI,8025,43504,349119600,0.181,20.97,2.92,1.31

In [73]:
sale_2419 = sale2.loc[2419]

In [74]:
sale_2420 = sale2.loc[2420]

In [79]:
print(f"it's a final 2 Premium_Share.\n its a return premium_share to...\n {sale_2419},\n\n\n{sale_2420}")

it's a final 2 Premium_Share.
 its a return premium_share to...
 Year                     2024
Month                       4
Region                    USA
Model                      X5
Units_Sold               4423
Avg_Price_EUR           68440
Revenue_EUR         302710120
BEV_Share               0.171
Premium_Share           20.97
GDP_Growth               2.92
Fuel_Price_Index         1.31
Name: 2419, dtype: object,


Year                     2024
Month                       4
Region                    USA
Model                      X7
Units_Sold              10053
Avg_Price_EUR           92764
Revenue_EUR         932556492
BEV_Share               0.145
Premium_Share           20.97
GDP_Growth               2.92
Fuel_Price_Index         1.31
Name: 2420, dtype: object

In [95]:
sale_low = bmw.query("`Premium_Share` < 5.10")

In [96]:
sale_low

,Year,Month,Region,Model,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
344,2018,11,RestOfWorld,3 Series,6644,49211,326957884,0.036,5.09,3.46,0.99
345,2018,11,RestOfWorld,5 Series,4111,62108,255325988,0.010,5.09,3.46,0.99
346,2018,11,RestOfWorld,X3,11048,59390,656140720,0.023,5.09,3.46,0.99
347,2018,11,RestOfWorld,X5,10166,68085,692152110,0.021,5.09,3.46,0.99
348,2018,11,RestOfWorld,X7,4149,93932,389723868,0.019,5.09,3.46,0.99
349,2018,11,RestOfWorld,i4,7532,63884,481174288,0.013,5.09,3.46,0.99
350,2018,11,RestOfWorld,iX,5760,75553,435185280,0.016,5.09,3.46,0.99
351,2018,11,RestOfWorld,MINI,8456,41911,354399416,0.019,5.09,3.46,0.99
3000,2025,10,RestOfWorld,3 Series,5827,47529,276951483,0.201,5.09,4.15,1.36
3001,2025,10,RestOfWorld,5 Series,9362,61073,571765426,0.196,5.09,4.15,1.36
3002,2025,10,RestOfWorld,X3,5109,56015,286180635,0.206,5.09,4.15,1.36
3003,2025,10,RestOfWorld,X5,6908,67845,468673260,0.203,5.09,4.15,1.36
3004,2025,10,RestOfWorld,X7,3525,93319,328949475,0.182,5.09,4.15,1.36
3005,2025,10,RestOfWorld,i4,5540,64646,358138840,0.185,5.09,4.15,1.36
3006,2025,10,RestOfWorld,iX,7367,73356,540413652,0.195,5.09,4.15,1.36
3007,2025,10,RestOfWorld,MINI,11477,41656,478085912,0.205,5.09,4.15,1.36

In [98]:
sale_low.head()

,Year,Month,Region,Model,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
344,2018,11,RestOfWorld,3 Series,6644,49211,326957884,0.036,5.09,3.46,0.99
345,2018,11,RestOfWorld,5 Series,4111,62108,255325988,0.010,5.09,3.46,0.99
346,2018,11,RestOfWorld,X3,11048,59390,656140720,0.023,5.09,3.46,0.99
347,2018,11,RestOfWorld,X5,10166,68085,692152110,0.021,5.09,3.46,0.99
348,2018,11,RestOfWorld,X7,4149,93932,389723868,0.019,5.09,3.46,0.99

In [99]:
sale_low.tail()

,Year,Month,Region,Model,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
3003,2025,10,RestOfWorld,X5,6908,67845,468673260,0.203,5.09,4.15,1.36
3004,2025,10,RestOfWorld,X7,3525,93319,328949475,0.182,5.09,4.15,1.36
3005,2025,10,RestOfWorld,i4,5540,64646,358138840,0.185,5.09,4.15,1.36
3006,2025,10,RestOfWorld,iX,7367,73356,540413652,0.195,5.09,4.15,1.36
3007,2025,10,RestOfWorld,MINI,11477,41656,478085912,0.205,5.09,4.15,1.36

In [106]:
one = sale_low.loc[345]
two = sale_low.loc[349]

In [108]:
print(f"it's a NonPremium_Share.\n its a return Lowest_premium_share to...\n {one}\n\n\n{two}")

it's a NonPremium_Share.
 its a return Lowest_premium_share to...
 Year                       2018
Month                        11
Region              RestOfWorld
Model                  5 Series
Units_Sold                 4111
Avg_Price_EUR             62108
Revenue_EUR           255325988
BEV_Share                  0.01
Premium_Share              5.09
GDP_Growth                 3.46
Fuel_Price_Index           0.99
Name: 345, dtype: object


Year                       2018
Month                        11
Region              RestOfWorld
Model                        i4
Units_Sold                 7532
Avg_Price_EUR             63884
Revenue_EUR           481174288
BEV_Share                 0.013
Premium_Share              5.09
GDP_Growth                 3.46
Fuel_Price_Index           0.99
Name: 349, dtype: object

In [110]:
bmw.describe()

,Year,Month,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
count,3072.000000,3072.000000,3072.000000,3072.000000,3.072000e+03,3072.000000,3072.000000,3072.000000,3072.000000
mean,2021.500000,6.500000,7980.288086,63854.561523,5.113995e+08,0.107572,14.660234,3.057526,1.176224
std,2.291661,3.452615,3174.917444,14655.891299,2.431185e+08,0.058099,5.334604,1.018103,0.118123
min,2018.000000,1.000000,2379.000000,40011.000000,1.045314e+08,-0.015000,5.090000,0.100000,0.920000
25%,2019.750000,3.750000,5225.500000,54500.250000,3.125504e+08,0.057000,12.275000,2.370000,1.080000
50%,2021.500000,6.500000,7985.500000,63493.000000,4.808690e+08,0.108000,16.260000,3.060000,1.180000
75%,2023.250000,9.250000,10528.250000,71489.500000,6.709141e+08,0.157250,18.932500,3.852500,1.270000
max,2025.000000,12.000000,15914.000000,93994.000000,1.433482e+09,0.223000,20.970000,5.820000,1.410000