In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("data_cleaning_sample.csv")

In [ ]:
print(df)

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [ ]:
df.head()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019

In [ ]:
df.tail()

      Name   Age      City Gender              Email   Join Date
4    David  22.0    Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0     Delhi      F     eve@domain.com         NaN
6    Alice  25.0  New York      F  alice@example.com  01-05-2021
7    Alice  25.0  New York      F  alice@example.com  01-05-2021
8  Charlie   NaN     Delhi      M    charlie@example  20-07-2021

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       8 non-null      object
 1   Age        6 non-null      float64
 2   City       9 non-null      object
 3   Gender     9 non-null      object
 4   Email      9 non-null      object
 5   Join Date  8 non-null      object
dtypes: float64(1), object(5)
memory usage: 564.0+ bytes

In [ ]:
df.loc[1]

Name                 Charlie
Age                      NaN
City                   Delhi
Gender                     M
Email        charlie@example
Join Date         20-07-2021
Name: 1, dtype: object

In [ ]:
df.loc[2]

Name                     Bob
Age                     30.0
City             Los Angeles
Gender                     M
Email        bob@example.com
Join Date         15-06-2020
Name: 2, dtype: object

In [ ]:
df.loc[3]

Name                 Charlie
Age                      NaN
City                   Delhi
Gender                     M
Email        charlie@example
Join Date         20-07-2021
Name: 3, dtype: object

In [ ]:
df.loc[4]

Name                     David
Age                       22.0
City                    Mumbai
Gender                       M
Email        david@example.com
Join Date           12-11-2019
Name: 4, dtype: object

In [ ]:
df.loc[5]

Name                    NaN
Age                    28.0
City                  Delhi
Gender                    F
Email        eve@domain.com
Join Date               NaN
Name: 5, dtype: object

In [ ]:
df.loc[6]

Name                     Alice
Age                       25.0
City                  New York
Gender                       F
Email        alice@example.com
Join Date           01-05-2021
Name: 6, dtype: object

In [ ]:
df.loc[7]

Name                     Alice
Age                       25.0
City                  New York
Gender                       F
Email        alice@example.com
Join Date           01-05-2021
Name: 7, dtype: object

In [ ]:
df.loc[8]

Name                 Charlie
Age                      NaN
City                   Delhi
Gender                     M
Email        charlie@example
Join Date         20-07-2021
Name: 8, dtype: object

In [ ]:
df.loc[0]

Name                     Alice
Age                       25.0
City                  New York
Gender                       F
Email        alice@example.com
Join Date           01-05-2021
Name: 0, dtype: object

In [ ]:
df.isnull()

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False