In [51]:
import numpy as np
import pandas as pd

In [52]:
df = pd.read_csv('iris.csv')

In [53]:
df.index

RangeIndex(start=0, stop=150, step=1)

In [54]:
df.columns

Index(['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width',
       'Species'],
      dtype='object')

In [55]:
type(df)

pandas.core.frame.DataFrame

In [56]:
df.head()

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [57]:
df.tail()

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sepal.Length  150 non-null    float64
 1   Sepal.Width   150 non-null    float64
 2   Petal.Length  150 non-null    float64
 3   Petal.Width   150 non-null    float64
 4   Species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [59]:
df.min()

Sepal.Length       4.3
Sepal.Width        2.0
Petal.Length       1.0
Petal.Width        0.1
Species         setosa
dtype: object

In [60]:
df.max()

Sepal.Length          7.9
Sepal.Width           4.4
Petal.Length          6.9
Petal.Width           2.5
Species         virginica
dtype: object

In [61]:
df.describe()

       Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [62]:
df.shape

(150, 5)

In [63]:
df['Sepal.Length'].copy()

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: Sepal.Length, Length: 150, dtype: float64

In [64]:
df['Sepal.Width'].copy()

0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ...
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: Sepal.Width, Length: 150, dtype: float64

In [65]:
df[["Sepal.Length","Sepal.Width"]].copy()

     Sepal.Length  Sepal.Width
0             5.1          3.5
1             4.9          3.0
2             4.7          3.2
3             4.6          3.1
4             5.0          3.6
..            ...          ...
145           6.7          3.0
146           6.3          2.5
147           6.5          3.0
148           6.2          3.4
149           5.9          3.0

[150 rows x 2 columns]

In [66]:
df.loc[0]

Sepal.Length       5.1
Sepal.Width        3.5
Petal.Length       1.4
Petal.Width        0.2
Species         setosa
Name: 0, dtype: object

In [67]:
df.loc[2]

Sepal.Length       4.7
Sepal.Width        3.2
Petal.Length       1.3
Petal.Width        0.2
Species         setosa
Name: 2, dtype: object

In [68]:
df[df['Sepal.Length']>7]

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
102           7.1          3.0           5.9          2.1  virginica
105           7.6          3.0           6.6          2.1  virginica
107           7.3          2.9           6.3          1.8  virginica
109           7.2          3.6           6.1          2.5  virginica
117           7.7          3.8           6.7          2.2  virginica
118           7.7          2.6           6.9          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
125           7.2          3.2           6.0          1.8  virginica
129           7.2          3.0           5.8          1.6  virginica
130           7.4          2.8           6.1          1.9  virginica
131           7.9          3.8           6.4          2.0  virginica
135           7.7          3.0           6.1          2.3  virginica

In [69]:
df[df['Sepal.Width']>5]

Empty DataFrame
Columns: [Sepal.Length, Sepal.Width, Petal.Length, Petal.Width, Species]
Index: []

In [72]:
df.query("`Sepal.Length` > 7.5")

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
105           7.6          3.0           6.6          2.1  virginica
117           7.7          3.8           6.7          2.2  virginica
118           7.7          2.6           6.9          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
131           7.9          3.8           6.4          2.0  virginica
135           7.7          3.0           6.1          2.3  virginica

In [84]:
df.query('`Sepal.Length` > 5 and `Sepal.Width`> 3')

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width     Species
0             5.1          3.5           1.4          0.2      setosa
5             5.4          3.9           1.7          0.4      setosa
10            5.4          3.7           1.5          0.2      setosa
14            5.8          4.0           1.2          0.2      setosa
15            5.7          4.4           1.5          0.4      setosa
16            5.4          3.9           1.3          0.4      setosa
17            5.1          3.5           1.4          0.3      setosa
18            5.7          3.8           1.7          0.3      setosa
19            5.1          3.8           1.5          0.3      setosa
20            5.4          3.4           1.7          0.2      setosa
21            5.1          3.7           1.5          0.4      setosa
23            5.1          3.3           1.7          0.5      setosa
27            5.2          3.5           1.5          0.2      setosa
28            5.2          3.4           1.4          0.2      setosa
31            5.4          3.4           1.5          0.4      setosa
32            5.2          4.1           1.5          0.1      setosa
33            5.5          4.2           1.4          0.2      setosa
36            5.5          3.5           1.3          0.2      setosa
39            5.1          3.4           1.5          0.2      setosa
44            5.1          3.8           1.9          0.4      setosa
46            5.1          3.8           1.6          0.2      setosa
48            5.3          3.7           1.5          0.2      setosa
50            7.0          3.2           4.7          1.4  versicolor
51            6.4          3.2           4.5          1.5  versicolor
52            6.9          3.1           4.9          1.5  versicolor
56            6.3          3.3           4.7          1.6  versicolor
65            6.7          3.1           4.4          1.4  versicolor
70            5.9          3.2           4.8          1.8  versicolor
85            6.0          3.4           4.5          1.6  versicolor
86            6.7          3.1           4.7          1.5  versicolor
100           6.3          3.3           6.0          2.5   virginica
109           7.2          3.6           6.1          2.5   virginica
110           6.5          3.2           5.1          2.0   virginica
115           6.4          3.2           5.3          2.3   virginica
117           7.7          3.8           6.7          2.2   virginica
120           6.9          3.2           5.7          2.3   virginica
124           6.7          3.3           5.7          2.1   virginica
125           7.2          3.2           6.0          1.8   virginica
131           7.9          3.8           6.4          2.0   virginica
136           6.3          3.4           5.6          2.4   virginica
137           6.4          3.1           5.5          1.8   virginica
139           6.9          3.1           5.4          2.1   virginica
140           6.7          3.1           5.6          2.4   virginica
141           6.9          3.1           5.1          2.3   virginica
143           6.8          3.2           5.9          2.3   virginica
144           6.7          3.3           5.7          2.5   virginica
148           6.2          3.4           5.4          2.3   virginica

In [85]:
df.at[20 , "Petal.Length"]

np.float64(1.7)

In [87]:
df.iat[20,2]

np.float64(1.7)

In [100]:
df.loc[1]

Sepal.Length       4.9
Sepal.Width        3.0
Petal.Length       1.4
Petal.Width        0.2
Species         setosa
Name: 1, dtype: object

In [95]:
df.iloc[20,2]

np.float64(1.7)