In [50]:
import pandas as pd

In [51]:
# Sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Math': [85, 78, 92],
    'Science': [90, 82, 89],
    'English': [88, 85, 94]
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)

      Name  Math  Science  English
0    Alice    85       90       88
1      Bob    78       82       85
2  Charlie    92       89       94

In [52]:
df.head()

      Name  Math  Science  English
0    Alice    85       90       88
1      Bob    78       82       85
2  Charlie    92       89       94

In [53]:
 df.melt(id_vars=["Name"] , value_vars=["Math","Science","English"], var_name="Subject",value_name = "Score")

      Name  Subject  Score
0    Alice     Math     85
1      Bob     Math     78
2  Charlie     Math     92
3    Alice  Science     90
4      Bob  Science     82
5  Charlie  Science     89
6    Alice  English     88
7      Bob  English     85
8  Charlie  English     94

In [55]:
df.melt(id_vars=["Name"],value_vars=["Math"],var_name="subject",value_name="score")

      Name subject  score
0    Alice    Math     85
1      Bob    Math     78
2  Charlie    Math     92

In [56]:
df.melt(id_vars=["Name"],value_vars=["Science"],var_name="subject",value_name="score")

      Name  subject  score
0    Alice  Science     90
1      Bob  Science     82
2  Charlie  Science     89

In [57]:
df.melt(id_vars="Name",value_vars="English",var_name="subject",value_name="score")

      Name  subject  score
0    Alice  English     88
1      Bob  English     85
2  Charlie  English     94

In [67]:


data = {
    "Name": ["Alice", "Bob", "Charlie", "Alice", "Bob", "Charlie", "Alice", "Bob", "Charlie"],
    "Subject": ["Math", "Math", "Math", "Science", "Science", "Science", "English", "English", "English"],
    "Score": [85, 78, 92, 90, 82, 89, 88, 85, 94]
}

df1 = pd.DataFrame(data)
df2 = pd.DataFrame(data)

print(df1)

      Name  Subject  Score
0    Alice     Math     85
1      Bob     Math     78
2  Charlie     Math     92
3    Alice  Science     90
4      Bob  Science     82
5  Charlie  Science     89
6    Alice  English     88
7      Bob  English     85
8  Charlie  English     94

In [64]:
#df.pivot(index = ['Name'],columns = 'subject',values='Score')
df1.pivot(index='Name', columns='Subject', values='Score')

Subject  English  Math  Science
Name
Alice         88    85       90
Bob           85    78       82
Charlie       94    92       89

In [68]:
df2.pivot(index='Name',columns='Subject',values='Score')

Subject  English  Math  Science
Name
Alice         88    85       90
Bob           85    78       82
Charlie       94    92       89